language: node_js
script:
  - yarn lint && yarn test
addons:
  apt:
    packages:
      - sshpass
env:
  - PASSWORD=$STAGING_SSH_PAASWORD
deploy:
  - provider: script
    script: yarn install && NODE_ENV=production yarn deploy
    on:
      branch: master
  - provider: script
    script: yarn install && NODE_ENV=staging yarn deploy
    on:
      branch: staging
  - provider: script
    script: yarn install && NODE_ENV=development yarn deploy
    on:
      branch: feature/16-deploy
notifications:
  email:
    recipients:
      - llauromanuel@gmail.com
      - dylanalvarez1995@gmail.com
      - sebastian.e.blanco@gmail.com
