language: node_js
script:
  - yarn lint && yarn test
notifications:
  email:
    recipients:
      - llauromanuel@gmail.com
      - dylanalvarez1995@gmail.com
      - sebastian.e.blanco@gmail.com
before_install:
  - openssl aes-256-cbc -K $encrypted_77965d5bdd4d_key -iv $encrypted_77965d5bdd4d_iv -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - echo -e "Host $SERVER_IP_ADDRESS\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - ssh-add ./deploy_key
deploy:
  - provider: script
    script: NODE_ENV=production yarn deploy
    on:
      branch: master
  - provider: script
    script: NODE_ENV=staging yarn deploy
    on:
      branch: staging
  - provider: script
      script: ssh -i ./deploy_key laboral@antiguos.fi.uba.ar 'touch test_file'
      on:
        branch: feature/16-deploy
