language: node_js
before_install:
  - openssl aes-256-cbc -K $encrypted_2580f7ff17f7_key -iv $encrypted_2580f7ff17f7_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
script:
- yarn lint && yarn test
deploy:
  - provider: script
    script:
      git clone https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=production yarn deploy:frontend
    on:
      branch: master
  - provider: script
    script:
      git clone https://github.com/fiuba-laboral-v2/deploy.git &&
      cd deploy &&
      yarn install &&
      NODE_ENV=staging yarn deploy:frontend
    on:
      branch: staging
notifications:
  email:
    recipients:
      - llauromanuel@gmail.com
      - dylanalvarez1995@gmail.com
      - sebastian.e.blanco@gmail.com
