language: node_js
before_install:
  - openssl aes-256-cbc -K $encrypted_2580f7ff17f7_key -iv $encrypted_2580f7ff17f7_iv
    -in deploy_key.enc -out ./deploy_key -d
  - eval "$(ssh-agent -s)"
  - chmod 600 ./deploy_key
  - ssh-add ./deploy_key
script:
- yarn lint && yarn test
addons:
  apt:
    packages:
    - sshpass
deploy:
- provider: script
  script: yarn install && NODE_ENV=production yarn deploy
  on:
    branch: master
- provider: script
  script: yarn install && NODE_ENV=staging yarn deploy
  on:
    branch: staging
- provider: script
  script: yarn install && NODE_ENV=development yarn deploy
  on:
    branch: feature/16-deploy
notifications:
  email:
    recipients:
    - llauromanuel@gmail.com
    - dylanalvarez1995@gmail.com
    - sebastian.e.blanco@gmail.com
