export enum ADMIN_LIST_COLUMNS_VALUES {
  NAME = "name",
  SURNAME = "surname",
  EMAIL = "email",
  SECRETARY = "secretary",
  CREATED_AT = "createdAt"
}

export const ADMIN_LIST_COLUMNS = [
  ADMIN_LIST_COLUMNS_VALUES.NAME,
  ADMIN_LIST_COLUMNS_VALUES.SURNAME,
  ADMIN_LIST_COLUMNS_VALUES.EMAIL,
  ADMIN_LIST_COLUMNS_VALUES.SECRETARY,
  ADMIN_LIST_COLUMNS_VALUES.CREATED_AT
];
