export enum COMPANY_USER_LIST_COLUMNS_VALUES {
  NAME = "name",
  EMAIL = "email",
  ROLE = "role",
  CREATED_AT = "createdAt"
}

export const COMPANY_USER_LIST_COLUMNS = [
  COMPANY_USER_LIST_COLUMNS_VALUES.NAME,
  COMPANY_USER_LIST_COLUMNS_VALUES.EMAIL,
  COMPANY_USER_LIST_COLUMNS_VALUES.ROLE,
  COMPANY_USER_LIST_COLUMNS_VALUES.CREATED_AT
];
