export const NEW_JOB_APPLICATION_COMPANY_NOTIFICATION = "NewJobApplicationCompanyNotification";
export type NEW_JOB_APPLICATION_COMPANY_NOTIFICATION_TYPE = "NewJobApplicationCompanyNotification";
export const COMPANY_APPROVED_OFFER_NOTIFICATION = "CompanyApprovedOfferNotification";
export type COMPANY_APPROVED_OFFER_NOTIFICATION_TYPE = "CompanyApprovedOfferNotification";
