export const COMPANY_NEW_JOB_APPLICATION_NOTIFICATION = "CompanyNewJobApplicationNotification";
export type COMPANY_NEW_JOB_APPLICATION_NOTIFICATION_TYPE = "CompanyNewJobApplicationNotification";
export const COMPANY_APPROVED_OFFER_NOTIFICATION = "CompanyApprovedOfferNotification";
export type COMPANY_APPROVED_OFFER_NOTIFICATION_TYPE = "CompanyApprovedOfferNotification";
