export enum JOB_APPLICATION_LIST_COLUMNS_VALUES {
  COMPANY_NAME = "companyName",
  CUIT = "cuit",
  APPLICANT_NAME = "applicantName",
  PADRON = "padron",
  STATUS = "approvalStatus",
  UPDATED_AT = "updatedAt",
  ACTIONS = "actions"
}

export const JOB_APPLICATION_LIST_COLUMNS = [
  JOB_APPLICATION_LIST_COLUMNS_VALUES.COMPANY_NAME,
  JOB_APPLICATION_LIST_COLUMNS_VALUES.CUIT,
  JOB_APPLICATION_LIST_COLUMNS_VALUES.APPLICANT_NAME,
  JOB_APPLICATION_LIST_COLUMNS_VALUES.PADRON,
  JOB_APPLICATION_LIST_COLUMNS_VALUES.STATUS,
  JOB_APPLICATION_LIST_COLUMNS_VALUES.UPDATED_AT,
  JOB_APPLICATION_LIST_COLUMNS_VALUES.ACTIONS
];
